name: Deploy Backend to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Deploy to EC2
        run: |
            echo "${{ secrets.SSH_KEY }}" > key.pem
            chmod 400 key.pem

            ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@${{ secrets.IP_HOST }} << 'EOF'
            cd cicd
            git pull origin main
            npm install
            npm run build
            pm2 restart all
            EOF